# Generated by Django 4.2.2 on 2023-08-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workoutlog_created_at_workoutlog_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='name',
            new_name='ExerciseName',
        ),
        migrations.RenameField(
            model_name='workoutlog',
            old_name='weight',
            new_name='Set1Weight',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='Set2Weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='Set3Weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='Set4Weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
